version: '3'

services:
  mediawiki:
    build:
      context: .
    restart: "no"
    environment:
      - MEDIAWIKI_SITE_NAME=My MediaWiki
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=mediawiki
      - MEDIAWIKI_DB_PASSWORD=mediawiki
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./composer.json:/var/www/html/composer.json
    links:
      - db:mysql
    ports:
      - "8080:80"

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mediawiki
      - MYSQL_ROOT_PASSWORD=root

  caddy:
    image: docker.io/library/caddy:2.4.6-alpine
    restart: unless-stopped
    entrypoint: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    environment:
      - MW_SITE_FQDN=ovh2024.geometryfactory.com
      - HTTPS_PORT=443
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
      - caddy-data:/data
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - mediawiki
    networks:
      - mediawiki-network

networks:
  mediawiki-network:

volumes:
  db-data:
  caddy-data: