version: '3'

services:
  mediawiki:
    build:
      context: .
    restart: always
    environment:
      - MEDIAWIKI_SITE_NAME=My MediaWiki
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=mediawiki
      - MEDIAWIKI_DB_PASSWORD=mediawiki
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./composer.json:/var/www/html/composer.json
    links:
      - db:mysql
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mediawiki
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: docker.io/library/caddy:2.8-alpine
    restart: unless-stopped
    entrypoint: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    environment:
      - MW_SITE_FQDN=${MW_SITE_FQDN}
      - HTTPS_PORT=${HTTPS_PORT}
      - CADDY_BASIC_AUTH_PASS=${CADDY_BASIC_AUTH_PASS}
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./caddy-data:/data
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - mediawiki

volumes:
  db-data:
  caddy-data: