version: '3'

services:
  mediawiki:
    build:
      context: .
    command: /usr/local/bin/scriptmediawiki.sh
    restart: "no"
    environment:
      - MEDIAWIKI_SITE_NAME=My MediaWiki
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=mediawiki
      - MEDIAWIKI_DB_PASSWORD=mediawiki
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./composer.json:/var/www/html/composer.json
    links:
      - db:mysql
    ports:
      - "8080:80"

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mediawiki
      - MYSQL_ROOT_PASSWORD=root