#
# Configuration for the CGAL editors wiki
#
Alias /CGAL/Editors/wiki /var/www/html/index.php
Alias /CGAL/Editors/w /var/www/html
Alias /CGAL/Editors/wiki-images /var/www/html/images

RedirectMatch permanent /CGAL/Editors/wiki/index.php/(.*)$ /CGAL/Editors/wiki/$1

# Enable the rewrite engine
RewriteEngine On

# Redirect / to Main Page
RewriteRule ^/*$ %{DOCUMENT_ROOT}/index.php [L]
